# Generated by Django 3.1.5 on 2021-02-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bill_bill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], default='EX', max_length=2),
        ),
    ]
