apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: bill
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bill
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bill
    spec:
      containers:
      - name: api
        image: bill-image
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["/bin/sh"]
        args: ["-c", "pwd && ls && sleep 10
                && pip install -r requirements.txt
                && python3 manage.py makemigrations
                && python3 manage.py migrate
                && python3 manage.py collectstatic --noinput
                && gunicorn --config=gunicorn_config.py backend.wsgi:application"]
        env:
        - name: DEBUG_FLAG
          value: 'true'
        - name: STATIC_URL
          value: /static/
        - name: GUNICORN_PORT
          value: '80'
        - name: GUNICORN_DEBUG_FLAG
          value: 'true'
        - name: GUNICORN_RELOAD_FLAG
          value: 'true'
        - name: SENTRY_DNS
          value: 'http://test.com'
        ports:
        - containerPort: 80