apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
spec:
  ports:
  selector:
    app.kubernetes.io/name: web
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
