apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
      - name: api
        image: web-image
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80