apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-v1
        image: zhuzean/bookkeeping:bill-svc
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["/bin/sh"]
        args: ["-c", "sleep 10
                && alembic upgrade head
                && uvicorn main:app --host 0.0.0.0 --port 8000"]
        env:
        - name: ENVIRONMENT
          value: 'production'
        - name: DATABASE_HOST
          value: '34.84.243.128'
        - name: DATABASE_PORT
          value: '5432'
        - name: DATABASE_NAME
          value: 'demo_microk8s'
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: pass
        ports:
        - containerPort: 8000
