apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-v1
        image: zhuzean/bookkeeping:bill-svc
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["/bin/sh"]
        args: ["-c", "sleep 10
                && pip install -r requirements.txt
                && python3 manage.py makemigrations
                && python3 manage.py migrate
                && python3 manage.py collectstatic --noinput
                && gunicorn --config=gunicorn_config.py backend.wsgi:application"]
        env:
        - name: DEBUG_FLAG
          value: 'true'
        - name: STATIC_URL
          value: /static/
        - name: GUNICORN_PORT
          value: '80'
        - name: GUNICORN_DEBUG_FLAG
          value: 'true'
        - name: GUNICORN_RELOAD_FLAG
          value: 'true'
        - name: SENTRY_DNS
          value: 'http://test.com'
        - name: DATABASE_HOST
          value: 'sh-cdb-qez3caps.sql.tencentcdb.com'
        - name: DATABASE_PORT
          value: '60187'
        - name: DATABASE_NAME
          value: 'zean_demo'
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: pass
        ports:
        - containerPort: 8000
